name: sogang_gsinfotech_com
description: sognag gsinfotech community application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  mvc_pattern: ^6.5.0
  fluttertoast: ^7.1.1
  firebase_auth: ^0.16.1
  flutter_signin_button: ^0.2.8
  google_sign_in: ^4.5.1
  google_fonts: ^1.1.0
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  image_picker: ^0.6.1+4
  table_calendar: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/images/
